services:
  - type: web
    name: comm-app-backend
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true
